/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package clientGui;

import client.ClientMain;
import clientGui.StudentFrame.MyCellRenderer;

import java.awt.Color;
import java.awt.Component;
import java.awt.event.ActionEvent;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.Vector;

import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.JTree;
import javax.swing.ListCellRenderer;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.tree.DefaultMutableTreeNode;

import univers.ClientSetUpPack;
import univers.Exercise;
import univers.Homework;
import univers.HomeworkInfo;
import univers.HomeworkPack;
import univers.OrderPack;
import univers.Question;
import univers.QuestionMapPack;
import univers.TalkPack;
import univers.User;


/**
 *
 * @author jackle
 */
public class TeacherFrame extends javax.swing.JFrame implements ClientFrame
{

    /**
     * Creates new form MainJFrame
     */
    public TeacherFrame(ClientMain _cm,User _user) 
    {
    	cm = _cm;
    	user = _user;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItem2 = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItem3 = new javax.swing.JCheckBoxMenuItem();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        onlineUserList = new javax.swing.JList();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jButton4 = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();
        jButton5 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jTextField2 = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane10 = new javax.swing.JScrollPane();
        jList3 = new javax.swing.JList();
        jButton6 = new javax.swing.JButton();
        jScrollPane9 = new javax.swing.JScrollPane();
        jPanel6 = new javax.swing.JPanel();
        jButton7 = new javax.swing.JButton();
        jScrollPane7 = new javax.swing.JScrollPane();
        jList4 = new javax.swing.JList();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        jCheckBoxMenuItem2.setSelected(true);
        jCheckBoxMenuItem2.setText("jCheckBoxMenuItem2");

        jCheckBoxMenuItem3.setSelected(true);
        jCheckBoxMenuItem3.setText("jCheckBoxMenuItem3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(200, 200, 800, 600));
        setLocation(new java.awt.Point(200, 150));
        setMinimumSize(new java.awt.Dimension(800, 600));
        setPreferredSize(new java.awt.Dimension(800, 600));
        setResizable(false);

        jTabbedPane1.setPreferredSize(new java.awt.Dimension(788, 588));

        jPanel4.setMaximumSize(new java.awt.Dimension(161, 421));
        jPanel4.setMinimumSize(new java.awt.Dimension(161, 421));

        jScrollPane3.setMaximumSize(new java.awt.Dimension(160, 411));
        jScrollPane3.setMinimumSize(new java.awt.Dimension(160, 411));
        jScrollPane3.setPreferredSize(new java.awt.Dimension(160, 411));
        jScrollPane3.setSize(new java.awt.Dimension(163, 411));
  
        //TODO onlineUserList
        onlineUserList.setCellRenderer(new MyCellRenderer());  
        onlineUserList.addMouseListener(new MouseListener() 
        {
			@Override
			public void mouseClicked(MouseEvent evt)  
			{ 
//				try {
					onlineUserSelect(evt);
//				} catch (IOException e) {
//					e.printStackTrace();
//				}
			}
			@Override
			public void mousePressed(MouseEvent e) { }
			@Override
			public void mouseReleased(MouseEvent e) { }
			@Override
			public void mouseEntered(MouseEvent e) { }
			@Override
			public void mouseExited(MouseEvent e) {	}
        });
        
        jScrollPane3.setViewportView(onlineUserList);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 411, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setFont(new java.awt.Font("Arial Hebrew", 1, 14));
        jScrollPane1.setViewportView(jTextArea1);

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane2.setViewportView(jTextArea2);

        jButton2.setText("Send");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) 
            {
                try 
                {
					jButton2ActionPerformed(evt);
				} 
                catch (IOException e) {
					e.printStackTrace();
				}
            }
        });
        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 493, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 79, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButton1.setText("Refresh");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
					jButton1ActionPerformed(evt);
				} catch (IOException e) {
					e.printStackTrace();
				}
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(user.getUserIcon())); // NOI18N
        jLabel1.setText(user.getUserName());
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addGap(28, 28, 28))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("    Talk    ", jPanel1);

        //TODO jList1
        
        jList1.addMouseListener(new java.awt.event.MouseAdapter() 
        {
            public void mouseClicked(java.awt.event.MouseEvent evt) 
            {
                try 
                {
					jList1MouseClicked(evt);
				} 
                catch (IOException e) {
					e.printStackTrace();
				}
            }
        });
        jList1.addListSelectionListener(new ListSelectionListener()
        {
			@Override
			public void valueChanged(ListSelectionEvent e) 
			{
				listSelection(e);
			}	
        });
        jScrollPane5.setViewportView(jList1);

        jButton4.setText("     ＋     ");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jTextField1.setText("");

        jLabel2.setText("Title");

        jLabel3.setText("Filed");

        jLabel4.setText("Content");

        jScrollPane6.setViewportView(jEditorPane1);

        jButton5.setText("Comfirm");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
					jButton5ActionPerformed(evt);
				} catch (IOException e) {
					e.printStackTrace();
				}
            }
        });

        jButton3.setText("Edit");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jTextField2.setText("");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField1)
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel4)
                                    .addGroup(jPanel8Layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(18, 18, 18)
                                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton5))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(5, 5, 5)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton5)
                    .addComponent(jButton3))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 467, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton4)
                        .addGap(17, 17, 17))))
        );

        jTabbedPane1.addTab("Questions", jPanel2);

        jScrollPane4.setHorizontalScrollBar(null);
        jScrollPane4.setPreferredSize(new java.awt.Dimension(170, 375));

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder("选择作业"));
        jPanel7.setPreferredSize(new java.awt.Dimension(150, 370));

        //TODO jList3
        jList3.addMouseListener(new java.awt.event.MouseAdapter() 
        {
            public void mouseClicked(java.awt.event.MouseEvent evt) 
            {
                try 
                {
					jList3MouseClicked(evt);
				} 
                catch (IOException e) {
					e.printStackTrace();
				}
            }
        });
        jList3.addListSelectionListener(new ListSelectionListener()
        {
			@Override
			public void valueChanged(ListSelectionEvent e) 
			{
				try {
					list3Selection(e);
				} catch (IOException e1) {
					// TODO Auto-generated catch block
					e1.printStackTrace();
				}
			}	
        });
        
        jScrollPane10.setViewportView(jList3);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane10, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane10, javax.swing.GroupLayout.DEFAULT_SIZE, 485, Short.MAX_VALUE)
        );

        jScrollPane4.setViewportView(jPanel7);

        jButton6.setText("Submit");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jPanel6.setPreferredSize(new java.awt.Dimension(450, 445));

        jButton7.setText("AddHomework");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        //TODO jList4
        jScrollPane7.setViewportView(jList4);

        jButton8.setText("AddExercise");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane7))
                .addGap(18, 18, 18)
                .addComponent(jButton8)
                .addContainerGap(355, Short.MAX_VALUE))
        );
        
        
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton7)
                    .addComponent(jButton8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 401, Short.MAX_VALUE)
                .addContainerGap())
        );

        jScrollPane9.setViewportView(jPanel6);

        jButton9.setText("CheckResult");

        //TODO
        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton6))
                    .addComponent(jScrollPane9, javax.swing.GroupLayout.DEFAULT_SIZE, 579, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton6)
                            .addComponent(jButton9))
                        .addGap(0, 14, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jTabbedPane1.addTab("    Class   ", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 571, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );
        
        jTextField1.setEditable(false);
        jTextField2.setEditable(false);
        jEditorPane1.setEditable(false);
        jButton5.setEnabled(false);
        jButton6.setEnabled(false);
        jButton8.setEnabled(false);
        
        pack();
        
    }
        
    
    private void onlineUserSelect(MouseEvent me)
    {
    	// TODO onlineUserSelect
    	System.out.println(onlineUserList.getSelectedValue());
    	
    	int to = (Integer)onlineUserList.getSelectedValue();
    	if(talkLog.get(to)!=null)
    	{
    		String c = talkLog.get(to).toString();
        	jTextArea1.setText(c);
    	}
    	else
    	{
    		talkLog.put(to, new StringBuffer());
    	}
    	jTextArea1.repaint();
    }
        

    

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) throws IOException
    {
        // TODO 刷新按钮的事件处理
    	onlineUserList.repaint();
    	cm.sendOutPack(new OrderPack(OrderPack.GETSETUPINFO,user.getUserNumber(),null));
    }
    
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) throws IOException 
    {
        // TODO send button
        int to = (Integer)onlineUserList.getSelectedValue();
    	TalkPack tp = new TalkPack(user.getUserNumber() ,to ,jTextArea2.getText());
        cm.sendOutPack(tp);
    	talkLog.get(to).append("你 ：\n"+jTextArea2.getText()+"\n");
    	String c = talkLog.get(to).toString();
    	jTextArea1.setText(c);
    	jTextArea2.setText("");
    }
    
    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) 
    {
        // TODO charge icon
        System.out.println("点击了头像");
        IconSelectFrame isf = new IconSelectFrame(this);
        isf.setLocationRelativeTo(null);
        isf.setVisible(true);
        
    }
    
    
    private boolean newQuestion = false;
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) 
    {
    	newQuestion = true;
        // TODO new question
    	jList1.setEnabled(false);
    	jTextField1.setEditable(true);
    	jTextField1.setText("添加标题");
    	jTextField2.setText(user.getField());
    	jButton3.setEnabled(false);
    	jButton5.setText("add Question");
    	jEditorPane1.setText("");
    	jEditorPane1.setEditable(true);
    	jButton5.setEnabled(true);
    	
    }

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) throws IOException 
    {
    	if(newQuestion)
    	{
    		 Question questionToSend = new Question(jTextField1.getText(),user.getField(),new StringBuffer(jEditorPane1.getText()),user.getUserNumber());
    		 int SendComfirm = JOptionPane.showConfirmDialog(null, "确认上传问题？", "提示",JOptionPane.YES_NO_CANCEL_OPTION);
	        	if(SendComfirm==0)
	        	{
	        		cm.sendOutPack(questionToSend);  
	            	questionList.remove(questionToSend.getTitle());
	            	questionList.put(questionToSend.getTitle(), questionToSend.getQuestionId());
	            	jButton5.setText("Comfirm");
	        	}
    		 
    	}
    	else
    	{
    		Object obj = jList1.getSelectedValue();
        	String title = (String)obj;
        	long num = questionList.get(title);
        	Question temque = questionMap.get(num);
        	
        	int SendComfirm;
        	SendComfirm = JOptionPane.showConfirmDialog(null, "确认上传问题？", "提示",JOptionPane.YES_NO_CANCEL_OPTION);
	        	if(SendComfirm==0)
	        	{
	        		temque.setTitle(jTextField1.getText());
	            	temque.setContent(new StringBuffer(jEditorPane1.getText()));
	            	cm.sendOutPack(temque);
	            	questionList.remove(temque.getTitle());
	            	questionList.put(temque.getTitle(), temque.getQuestionId());
	        	}
        	
    	}
    	jEditorPane1.setEditable(false);
    	jTextField1.setEditable(false);
    	jList1.setEnabled(true);
    	jButton5.setEnabled(false);
    	jButton3.setEnabled(true);
    	jButton8.setEnabled(false);
        // TODO 确认
    	
    }


    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) 
    {
        // TODO 编辑
    	jEditorPane1.setEditable(true);
    	jTextField1.setEditable(true);
    	jList1.setEnabled(false);
    	jButton5.setEnabled(true);
    	jButton3.setEnabled(false);
    }

    
    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) 
    {
    	
    	try 
    	{
			cm.sendOutPack(hw);
			jList3.setEnabled(true);
			jButton7.setEnabled(true);
			jButton8.setEnabled(false);
			jButton9.setEnabled(true);
			jButton6.setEnabled(true);
		} 
    	catch (IOException e) 
		{
			e.printStackTrace();
		}
    	
    }


    
    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) 
    {
    	jList3.setEnabled(false);
    	jButton6.setEnabled(true);
    	jButton7.setEnabled(false);
    	jButton8.setEnabled(true);
    	jButton9.setEnabled(false);
    	hw = new Homework(user.getField(),JOptionPane.showInputDialog("新建作业的名字为"));
        // TODO add your handling code here:
    }

    
    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) 
    {
        // TODO add your handling code here:
    	BuildExercise be = new BuildExercise(this);
    	exVector = new Vector<Exercise>();
    	be.setVisible(true);
    	be.show();
    }
    
    protected void addNewExercise(Exercise ex)
    {
    	exVector.add(ex);
    	hw.addExersice(ex);
    	jList4.setListData(exVector);
    	jList4.repaint();
    	
    }
    

    private long timeInterval = new Date().getTime()-30000;
    private void jList1MouseClicked(java.awt.event.MouseEvent evt) throws IOException 
    {
        // TODO jList1.mouseclicked
        timeInterval = new Date().getTime()-timeInterval;
    	if(timeInterval>30000)
    	{
    		cm.sendOutPack(new OrderPack(0,user.getUserNumber(),user.getField()));
    	}
    	timeInterval = new Date().getTime();
    }
    
    private void listSelection(ListSelectionEvent e)
    {
    	//TODO listSelection
    	Object obj = jList1.getSelectedValue();
    	String title = (String)obj;
    	long num = questionList.get(title);
    	Question temque = questionMap.get(num);
    	jTextField1.setText(temque.getTitle());
    	jEditorPane1.setText(temque.getContent().toString());
    	
    }

    /**
     * @param args the command line arguments
     * @throws IOException 
     */
    private void list3Selection(ListSelectionEvent e) throws IOException
    {
    	Object obj = jList1.getSelectedValue();
    	HomeworkInfo work = (HomeworkInfo)obj;
    	if(hwmap.containsKey(work.getNum()))
    	{
    		Homework hmwork = hwmap.get(work.getNum());
    		exVector = new Vector<Exercise>(hmwork.getExerciseList());
    		jList4.setListData(exVector);
    		jList4.repaint();
    	}
    	else
    	{
        	cm.sendOutPack(new OrderPack(OrderPack.GETTHEHOMEWORK,user.getUserNumber(),work.getNum()+""));
    	}
    	
    }
  
    
    
    private long timeInterval2 = new Date().getTime()-30000;
    private void jList3MouseClicked(java.awt.event.MouseEvent evt) throws IOException 
    {
        // TODO jList1.mouseclicked
        timeInterval2 = new Date().getTime()-timeInterval2;
    	if(timeInterval2>30000)
    	{
    		cm.sendOutPack(new OrderPack(OrderPack.GETHOMEWORK,user.getUserNumber(),user.getField()));
    	}
    	timeInterval2 = new Date().getTime();
    }

    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem2;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem3;
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JList jList1;
    private javax.swing.JList jList3;
    private javax.swing.JList jList4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JList onlineUserList;
    
    
	public ClientMain cm;
	public HashMap<Integer,StringBuffer> talkLog = new HashMap<Integer,StringBuffer>();
	private HashMap<String,Long> questionList = new HashMap<String,Long>();//questionTitle to questionId
	private HashMap<Long,Question> questionMap;
	
	private HashMap<Long,Homework> hwmap = new HashMap<Long,Homework>();
	private Vector<Exercise> exVector;
	private Homework hw; 
	private User user;
    
	@Override
	public void SetUpClientUI(ClientSetUpPack csup)
    {
    	
    	cm.IconMap = csup.getIconMap();
    	cm.NameMap = csup.getNameMap();
    	Vector<Integer> listData = new Vector<Integer>(cm.IconMap.keySet());
    	onlineUserList.setListData(listData); 
    	
    }

	@Override
	public void newMessage(TalkPack tp)
    {
    	String from = cm.NameMap.get(tp.getFrom());
    	String content = tp.getContent();
    	if(talkLog.get(tp.getFrom())!=null)
    	{
    		talkLog.get(tp.getFrom()).append(from+"：\n"+content+"\n");
        	jTextArea1.setText(talkLog.get(tp.getFrom()).toString());
    	}
    	else
    	{
    		talkLog.put(tp.getFrom(), new StringBuffer());
    		talkLog.get(tp.getFrom()).append(from+"：\n"+content+"\n");
        	jTextArea1.setText(talkLog.get(tp.getFrom()).toString());
    	}
    	jTextArea1.repaint();
    }


	@Override
	public void setIcon(String icon)
    {
    	
    	try 
    	{
    		jLabel1.setIcon(new ImageIcon(icon));
        	jLabel1.repaint();
			cm.sendOutPack(new OrderPack(OrderPack.CHANGEICON,user.getUserNumber(),icon));
		} 
    	catch (IOException e) 
    	{
			e.printStackTrace();
		}
    }

	@Override
	public void setUpQuestion(QuestionMapPack fp) 
	{
		// TODO Auto-generated method stub
		questionMap = fp.getQmp();
		ArrayList<Long> numbers = new ArrayList<Long>(questionMap.keySet());
		System.out.println("收到questionmap大小"+numbers.size());
		Vector<String> titles = new Vector<String>();
		for(long l : numbers)
		{
			Question tq = questionMap.get(l);
			questionList.put(tq.getTitle(), tq.getQuestionId());
			titles.add(tq.getTitle());
		}
		jList1.setListData(titles);
	}

	
	class MyCellRenderer extends JLabel implements ListCellRenderer<Object> 
	{
	    public MyCellRenderer() 
	    {
	        setOpaque(true);
	        setFont(new java.awt.Font("Arial Hebrew", 1, 20));        
	    }

	    public Component getListCellRendererComponent(  JList<?> list,
									                    Object value,
									                    int index,
									                    boolean isSelected,
									                    boolean cellHasFocus) 
	    {
	    	if (value != null)   
			{   
	    		Integer num = (Integer)value;
				setText(cm.NameMap.get(num));   
				setIcon(new ImageIcon(cm.IconMap.get(num)));
	  
			}           
			if (isSelected)   
			{   
				setBackground(list.getSelectionBackground());   
				setForeground(list.getSelectionForeground());   
			}   
		  	else
			{                
				//设置选取与取消选取的前景与背景颜色.   
				setBackground(list.getBackground());   
				setForeground(list.getForeground());   
			}   
			return this;  

	    }
	}


	@Override
	public void setHomework(HomeworkPack hp) 
	{
		ArrayList<HomeworkInfo> homeInfo = hp.getHomeworkPack();
		Vector<HomeworkInfo> info = new Vector<HomeworkInfo>(homeInfo);
		jList3.setListData(info);
		jList3.repaint();
	}

}
